name: wikapediaracer
description: "Helping you race though wikapedia"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  share_plus: ^7.2.1
  uuid: ^4.1.0
  json_annotation: ^4.8.1
  flutter_native_splash: ^2.4.6
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/

flutter_native_splash:
  # Background color using the app's primary theme
  color: "#2563EB"  # Primary blue matching the app theme
  color_dark: "#1E293B"  # Dark blue for dark mode
  
  # Fullscreen for a clean look
  fullscreen: true
  
  # Android 12+ adaptive icon support
  android_12:
    icon_background_color: "#2563EB"
    icon_background_color_dark: "#1E293B"
  
  # Enable for supported platforms
  web: true
  android: true
  ios: true
